spring:
  profiles:
    active: local

logging:
  level:
    root: warn

custom:
  property:
    single: custom-property
    comlist: comma,sparatedmlist,to,value
    ncp:
      id: api-id
      key: api-key
      url: https://ncp.com/
# custom.property.single
# custom.property.comlist